version: '3.8'
services:

  garage-app-nginx:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
      target: develop
    image: dowhilenotdone/nginx:latest    
    container_name: garage-app-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8881:8881"
      - "8443:443"
    volumes:
        - ./:/var/www
        - ./docker/config/nginx/conf.d/garagetest.conf:/etc/nginx/conf.d/default.conf:ro
        - ./docker/config/nginx/conf.d/mime.types:/etc/nginx/conf.d/mime.types:ro
  garage-app-php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php-fpm/Dockerfile
      target: develop
    image: dowhilenotdone/php-fpm:latest
    container_name: garage-app-php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  garage-app-mysql:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
      target: develop
    image: dowhilenotdone/mysql:latest
    container_name: garage-app-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - $PWD/docker/volumes/mysql:/var/lib/mysql
      - $PWD/docker/config/mysql/my.cnf:/etc/mysql/my.cnf
      - $PWD/docker/config/mysql/init/create-databases.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass

  garage-app-mailtrap:
    image: eaudeweb/mailtrap:latest
    container_name: garage-app-mailtrap
    environment:
      - MT_USER=mailtrap
      - MT_PASSWD=mailtrap
    ports:
      - "2225:25"
      - "8882:80"

  garage-app-selenium:
    container_name: garage-app-selenium
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
    shm_size: '2gb'
